# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mapReduce.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmapReduce.proto\x12\tmapreduce\"R\n\nMapRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05start\x18\x02 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x05\x12\x11\n\tcentroids\x18\x04 \x01(\t\x12\t\n\x01r\x18\x05 \x01(\x05\"\x1e\n\x0bMapResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"1\n\rReduceRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0cmapper_nodes\x18\x02 \x01(\t\"4\n\x0eReduceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tcentroids\x18\x02 \x01(\t\"\x1f\n\x11GetEntriesRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x12GetEntriesResponse\x12\x0f\n\x07\x65ntries\x18\x01 \x01(\t2\xd1\x01\n\tMapReduce\x12\x36\n\x03Map\x12\x15.mapreduce.MapRequest\x1a\x16.mapreduce.MapResponse\"\x00\x12?\n\x06Reduce\x12\x18.mapreduce.ReduceRequest\x1a\x19.mapreduce.ReduceResponse\"\x00\x12K\n\nGetEntries\x12\x1c.mapreduce.GetEntriesRequest\x1a\x1d.mapreduce.GetEntriesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapReduce_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MAPREQUEST']._serialized_start=30
  _globals['_MAPREQUEST']._serialized_end=112
  _globals['_MAPRESPONSE']._serialized_start=114
  _globals['_MAPRESPONSE']._serialized_end=144
  _globals['_REDUCEREQUEST']._serialized_start=146
  _globals['_REDUCEREQUEST']._serialized_end=195
  _globals['_REDUCERESPONSE']._serialized_start=197
  _globals['_REDUCERESPONSE']._serialized_end=249
  _globals['_GETENTRIESREQUEST']._serialized_start=251
  _globals['_GETENTRIESREQUEST']._serialized_end=282
  _globals['_GETENTRIESRESPONSE']._serialized_start=284
  _globals['_GETENTRIESRESPONSE']._serialized_end=321
  _globals['_MAPREDUCE']._serialized_start=324
  _globals['_MAPREDUCE']._serialized_end=533
# @@protoc_insertion_point(module_scope)
