all:
	make clean
	
0:
	python3 final_code_S1.py --node_id 0 --node_ip 10.128.0.3 --node_port 60000

1:
	python3 final_code_S1.py --node_id 1 --node_ip 10.128.0.4 --node_port 60001

2:
	python3 final_code_S1.py --node_id 2 --node_ip 10.128.0.5 --node_port 60002

3:
	python3 final_code_S1.py --node_id 3 --node_ip 10.128.0.6 --node_port 60003

4:
	python3 final_code_S1.py --node_id 4 --node_ip 10.128.0.7 --node_port 60004

clean:
	echo -n '' > logs_node_0/logs.txt
	echo -n '' > logs_node_0/metadata.txt
	echo -n '' > logs_node_0/dump.txt

	echo -n '' > logs_node_1/logs.txt
	echo -n '' > logs_node_1/metadata.txt
	echo -n '' > logs_node_1/dump.txt

	echo -n '' > logs_node_2/logs.txt
	echo -n '' > logs_node_2/metadata.txt
	echo -n '' > logs_node_2/dump.txt

	echo -n '' > logs_node_3/logs.txt
	echo -n '' > logs_node_3/metadata.txt
	echo -n '' > logs_node_3/dump.txt
	
	echo -n '' > logs_node_4/logs.txt
	echo -n '' > logs_node_4/metadata.txt
	echo -n '' > logs_node_4/dump.txt