# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import buyer_pb2 as buyer__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmarket.proto\x12\x06market\x1a\x0b\x62uyer.proto\"\x84\x02\n\x18NotifyClientNotification\x12;\n\x0cupdated_item\x18\x01 \x01(\x0b\x32%.market.NotifyClientNotification.Item\x12\x16\n\x0erecipient_type\x18\x02 \x01(\t\x1a\x92\x01\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x1a\n\x12quantity_remaining\x18\x06 \x01(\x05\x12\x0e\n\x06seller\x18\x07 \x01(\t\x12\x0e\n\x06rating\x18\x08 \x01(\x01\"&\n\x14NotifyClientResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2_\n\rMarketService\x12N\n\x0cNotifyClient\x12 .market.NotifyClientNotification\x1a\x1c.market.NotifyClientResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOTIFYCLIENTNOTIFICATION']._serialized_start=38
  _globals['_NOTIFYCLIENTNOTIFICATION']._serialized_end=298
  _globals['_NOTIFYCLIENTNOTIFICATION_ITEM']._serialized_start=152
  _globals['_NOTIFYCLIENTNOTIFICATION_ITEM']._serialized_end=298
  _globals['_NOTIFYCLIENTRESPONSE']._serialized_start=300
  _globals['_NOTIFYCLIENTRESPONSE']._serialized_end=338
  _globals['_MARKETSERVICE']._serialized_start=340
  _globals['_MARKETSERVICE']._serialized_end=435
# @@protoc_insertion_point(module_scope)
